# kenmacpherson.com nginx config
server {
    listen 80;
    server_name kenmacpherson.com www.kenmacpherson.com;
    root /var/www/kenmacpherson.com;
    index index.html index.htm;

    access_log /var/log/nginx/kenmacpherson.com.access.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
