# oakland.center nginx config
server {
    listen 80;
    server_name oakland.center www.oakland.center;
    root /var/www/oakland.center;
    index index.html index.htm;

    access_log /var/log/nginx/oakland.center.access.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
